const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('vi-VN').format(Math.round(Number(n)||0))+' đ';
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);

const categories={
 income:[['Lương','💼'],['Thưởng','🎁'],['Làm tự do','💻'],['Cho thuê','🏢'],['Khác','➕']],
 expense:[['Ăn uống','🍴'],['Di chuyển','🚗'],['Nhà ở','🏠'],['Hóa đơn','📄'],['Mua sắm','🛍'],['Giải trí','🎮'],['Sức khỏe','✚'],['Giáo dục','📚'],['Khác','•••']],
 transfer:[['Chuyển khoản','↔']]
};
const quickDefaults=[['Ăn uống',1200000],['Di chuyển',1500000],['Hóa đơn',1000000],['Giải trí',500000]];
const defaults={
 wallets:[{id:'cash',name:'Tiền mặt',kind:'Tiền mặt',balance:0},{id:'mb',name:'MB Bank',kind:'Ngân hàng',balance:82000},{id:'vcb',name:'Vietcombank',kind:'Ngân hàng',balance:0}],
 transactions:[],
 budgets:[{id:'b1',category:'Di chuyển',limit:1500000}],
 settings:{theme:'dark',hideBalance:false}
};
let state=load(),period='month',filter='all',chartMode='flow',txType='income',selectedCategory='Lương';

function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem('aiFinanceIOS')||'{}')}}catch{return structuredClone(defaults)}}
function persist(){localStorage.setItem('aiFinanceIOS',JSON.stringify(state));render()}
function walletBalance(id){const w=state.wallets.find(x=>x.id===id);let bal=Number(w?.balance)||0;state.transactions.forEach(t=>{if(t.type==='income'&&t.wallet===id)bal+=t.amount;if(t.type==='expense'&&t.wallet===id)bal-=t.amount;if(t.type==='transfer'){if(t.wallet===id)bal-=t.amount;if(t.toWallet===id)bal+=t.amount}});return bal}
function totalAssets(){return state.wallets.reduce((a,w)=>a+walletBalance(w.id),0)}
function rangeStart(){const d=new Date();if(period==='week'){const day=d.getDay()||7;d.setDate(d.getDate()-day+1)}if(period==='month')d.setDate(1);if(period==='year'){d.setMonth(0);d.setDate(1)}d.setHours(0,0,0,0);return d}
function inPeriod(t){return new Date(t.date+'T00:00:00')>=rangeStart()}
function totals(){const ts=state.transactions.filter(inPeriod);return{income:ts.filter(t=>t.type==='income').reduce((a,b)=>a+b.amount,0),expense:ts.filter(t=>t.type==='expense').reduce((a,b)=>a+b.amount,0)}}
function iconFor(cat){for(const arr of Object.values(categories)){const x=arr.find(c=>c[0]===cat);if(x)return x[1]}return'•'}
function openScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$$('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));window.scrollTo({top:0,behavior:'smooth'})}
function transactionHtml(t){const sign=t.type==='income'?'+':t.type==='expense'?'-':'';const cls=t.type;const wallet=state.wallets.find(w=>w.id===t.wallet)?.name||'';return `<div class="transaction-item"><div class="tx-icon">${iconFor(t.category)}</div><div class="tx-main"><strong>${t.category}</strong><small>${t.note||wallet} · ${new Date(t.date).toLocaleDateString('vi-VN')}</small></div><div class="tx-value ${cls}">${sign}${money(t.amount)}</div></div>`}
function renderTransactions(){let list=[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt);$('#recentList').innerHTML=list.length?list.slice(0,4).map(transactionHtml).join(''):`<div class="empty"><strong>Chưa có giao dịch</strong>Nhấn dấu + để thêm giao dịch đầu tiên.</div>`;const q=$('#transactionSearch').value.trim().toLowerCase();list=list.filter(t=>(filter==='all'||t.type===filter)&&(!q||`${t.category} ${t.note||''}`.toLowerCase().includes(q)));$('#transactionList').innerHTML=list.length?list.map(transactionHtml).join(''):`<div class="empty"><strong>Không có giao dịch</strong>Hãy thử bộ lọc khác.</div>`}
function renderWallets(){const q=$('#walletSearch').value.trim().toLowerCase();const list=state.wallets.filter(w=>w.name.toLowerCase().includes(q));$('#walletList').innerHTML=list.map(w=>`<div class="wallet-card"><div class="icon">${w.kind==='Ngân hàng'?'🏦':w.kind==='Ví điện tử'?'📱':'💵'}</div><div><strong>${w.name}</strong><small>${w.kind}</small></div><b>${money(walletBalance(w.id))}</b></div>`).join('')}
function monthExpense(cat){const n=new Date();return state.transactions.filter(t=>t.type==='expense'&&t.category===cat&&new Date(t.date).getMonth()===n.getMonth()&&new Date(t.date).getFullYear()===n.getFullYear()).reduce((a,b)=>a+b.amount,0)}
function renderBudgets(){const total=state.budgets.reduce((a,b)=>a+b.limit,0),spent=state.budgets.reduce((a,b)=>a+monthExpense(b.category),0),pct=total?Math.round(spent/total*100):0,score=Math.max(0,Math.min(100,100-Math.max(0,pct-50)));$('#budgetScore').textContent=score;$('#budgetHealthBar').style.width=score+'%';$('#budgetTotal').textContent=money(total);$('#budgetSpent').textContent=money(spent);$('#budgetLeft').textContent=money(Math.max(0,total-spent));$('#budgetPercent').textContent=pct+'%';$('#budgetList').innerHTML=state.budgets.map(b=>{const s=monthExpense(b.category),p=Math.min(100,b.limit?Math.round(s/b.limit*100):0);return `<div class="budget-card"><div class="budget-card-top"><div class="budget-card-title"><div class="tx-icon">${iconFor(b.category)}</div><div><strong>${b.category}</strong><div style="color:var(--muted);margin-top:4px">Tháng này</div></div></div><b>${money(s)}</b></div><div class="progress"><i style="width:${p}%;background:${p>=100?'var(--red)':p>=80?'var(--orange)':'var(--green)'}"></i></div><div class="budget-meta"><span>${p}%</span><span>Tổng: ${money(b.limit)}</span></div></div>`}).join('')||`<div class="empty"><strong>Chưa có ngân sách</strong>Nhấn + để tạo ngân sách.</div>`}
function renderQuick(){const host=$('#quickGrid');host.innerHTML=quickDefaults.map(([cat,limit])=>{const on=state.budgets.some(b=>b.category===cat);return `<button class="quick-chip ${on?'selected':''}" data-qcat="${cat}" data-limit="${limit}"><span class="tick">${on?'✓':'+'}</span><span class="qicon">${iconFor(cat)}</span><span>${cat}</span></button>`}).join('');$$('[data-qcat]').forEach(b=>b.onclick=()=>{const found=state.budgets.find(x=>x.category===b.dataset.qcat);if(found)state.budgets=state.budgets.filter(x=>x.id!==found.id);else state.budgets.push({id:uid(),category:b.dataset.qcat,limit:Number(b.dataset.limit)});persist()})}
function updateAI(){const t=totals();let text='Thêm giao dịch để robot AI phân tích thu chi cho bạn.';if(state.transactions.length){const net=t.income-t.expense;if(t.expense===0)text=`Bạn đã ghi nhận ${money(t.income)} thu nhập và chưa có chi tiêu trong kỳ này.`;else if(net>=0)text=`Bạn đang dư ${money(net)}. Chi tiêu chiếm ${Math.round(t.expense/Math.max(1,t.income)*100)}% thu nhập.`;else text=`Chi tiêu đang vượt thu nhập ${money(Math.abs(net))}. Nên xem lại các danh mục lớn nhất.`}$('#aiInsight').textContent=text;$('#aiPanelText').textContent=text}
function render(){document.body.classList.toggle('light',state.settings.theme==='light');$('#themeLabel').textContent=state.settings.theme==='light'?'Sáng':'Tối';const t=totals();$('#totalBalance').textContent=state.settings.hideBalance?'••••••':money(totalAssets());$('#incomeValue').textContent=money(t.income);$('#expenseValue').textContent=money(t.expense);$('#walletTotal').textContent=money(totalAssets());$('#walletCount').textContent=state.wallets.length+' tài khoản';renderTransactions();renderWallets();renderBudgets();renderQuick();updateAI();drawChart()}
function drawChart(){const c=$('#chart'),ratio=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*ratio;c.height=h*ratio;const ctx=c.getContext('2d');ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);ctx.font='12px -apple-system';if(chartMode==='flow'){const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d}),vals=days.map(d=>{const ds=d.toISOString().slice(0,10),ts=state.transactions.filter(t=>t.date===ds);return[ts.filter(t=>t.type==='income').reduce((a,b)=>a+b.amount,0),ts.filter(t=>t.type==='expense').reduce((a,b)=>a+b.amount,0)]}),max=Math.max(1,...vals.flat()),base=h-28,gh=h-55,group=w/7;ctx.strokeStyle='#36383d';ctx.setLineDash([5,6]);for(let i=0;i<4;i++){const y=18+i*gh/3;ctx.beginPath();ctx.moveTo(30,y);ctx.lineTo(w-8,y);ctx.stroke()}ctx.setLineDash([]);vals.forEach((v,i)=>{const bw=Math.min(16,group*.24),x=i*group+group*.31;ctx.fillStyle='#4fc35a';roundRect(ctx,x,base-v[0]/max*gh,bw,v[0]/max*gh,6);ctx.fill();ctx.fillStyle='#ff5149';roundRect(ctx,x+bw+5,base-v[1]/max*gh,bw,v[1]/max*gh,6);ctx.fill();ctx.fillStyle='#4fa8a3';ctx.fillText(['CN','T2','T3','T4','T5','T6','T7'][days[i].getDay()],x,h-6)})}else{const sums={};state.transactions.filter(t=>t.type==='expense'&&inPeriod(t)).forEach(t=>sums[t.category]=(sums[t.category]||0)+t.amount);const arr=Object.entries(sums).sort((a,b)=>b[1]-a[1]),total=arr.reduce((a,b)=>a+b[1],0);if(!arr.length){ctx.fillStyle='#888';ctx.fillText('Chưa có dữ liệu chi tiêu',w/2-70,h/2);return}const colors=['#9c27b0','#ff5722','#03a9f4','#4caf50','#ffc107'];let start=-Math.PI/2;arr.forEach(([k,v],i)=>{const a=v/total*Math.PI*2;ctx.beginPath();ctx.strokeStyle=colors[i%colors.length];ctx.lineWidth=34;ctx.arc(w*.28,h*.52,66,start,start+a);ctx.stroke();start+=a});arr.slice(0,5).forEach(([k,v],i)=>{ctx.fillStyle=colors[i%colors.length];ctx.beginPath();ctx.arc(w*.58,45+i*30,6,0,Math.PI*2);ctx.fill();ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--text');ctx.fillText(`${k} ${Math.round(v/total*100)}%`,w*.62,49+i*30)})}}
function roundRect(ctx,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath()}
function openSheet(el){$('#sheetBackdrop').classList.add('show');el.classList.add('show');el.setAttribute('aria-hidden','false')}
function closeSheets(){$('#sheetBackdrop').classList.remove('show');$$('.bottom-sheet').forEach(s=>{s.classList.remove('show');s.setAttribute('aria-hidden','true')})}
function populateWallets(){const opts=state.wallets.map(w=>`<option value="${w.id}">${w.name}</option>`).join('');$('#walletSelect').innerHTML=opts;$('#toWalletSelect').innerHTML=opts}
function setTxType(type){txType=type;selectedCategory=categories[type][0][0];$$('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$('#toWalletField').hidden=type!=='transfer';renderCategories()}
function renderCategories(){$('#categoryGrid').innerHTML=categories[txType].map(([name,icon])=>`<button class="category-option ${name===selectedCategory?'selected':''}" data-cat="${name}"><span class="cat-icon">${icon}</span><span>${name}</span></button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.cat;renderCategories()})}

$$('[data-tab]').forEach(b=>b.onclick=()=>openScreen(b.dataset.tab));
$$('[data-screen-link]').forEach(b=>b.onclick=()=>openScreen(b.dataset.screenLink));
$$('[data-period]').forEach(b=>b.onclick=()=>{$$('[data-period]').forEach(x=>x.classList.remove('active'));b.classList.add('active');period=b.dataset.period;render()});
$$('[data-chart-mode]').forEach(b=>b.onclick=()=>{$$('[data-chart-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');chartMode=b.dataset.chartMode;drawChart()});
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderTransactions()});
$('#transactionSearch').oninput=renderTransactions;$('#walletSearch').oninput=renderWallets;
$('#addTransaction').onclick=()=>{populateWallets();$('#dateInput').value=today();setTxType('income');openSheet($('#transactionSheet'))};
$('#closeTransactionSheet').onclick=closeSheets;$$('[data-close-sheet]').forEach(b=>b.onclick=closeSheets);$('#sheetBackdrop').onclick=closeSheets;
$$('[data-type]').forEach(b=>b.onclick=()=>setTxType(b.dataset.type));
$('#saveTransaction').onclick=()=>{const amount=Number($('#amountInput').value.replace(/\D/g,''));if(!amount)return alert('Nhập số tiền hợp lệ');state.transactions.push({id:uid(),type:txType,category:selectedCategory,amount,wallet:$('#walletSelect').value,toWallet:$('#toWalletSelect').value,date:$('#dateInput').value||today(),note:$('#noteInput').value.trim(),createdAt:Date.now()});$('#amountInput').value='';$('#noteInput').value='';closeSheets();persist()};
$('#addWallet').onclick=()=>openSheet($('#walletSheet'));$('#saveWallet').onclick=()=>{const name=$('#walletName').value.trim();if(!name)return alert('Nhập tên tài khoản');state.wallets.push({id:uid(),name,kind:$('#walletKind').value,balance:Number($('#walletInitial').value.replace(/\D/g,''))||0});$('#walletName').value='';$('#walletInitial').value='';closeSheets();persist()};
$('#addBudget').onclick=()=>{$('#budgetCategory').innerHTML=categories.expense.filter(([n])=>!state.budgets.some(b=>b.category===n)).map(([n])=>`<option>${n}</option>`).join('');openSheet($('#budgetSheet'))};$('#saveBudget').onclick=()=>{const limit=Number($('#budgetLimit').value.replace(/\D/g,''));if(!limit)return alert('Nhập giới hạn');state.budgets.push({id:uid(),category:$('#budgetCategory').value,limit});$('#budgetLimit').value='';closeSheets();persist()};
$('#toggleBalance').onclick=()=>{state.settings.hideBalance=!state.settings.hideBalance;persist()};
$('#openAI').onclick=$('#robotOrb').onclick=()=>{$('#sheetBackdrop').classList.add('show');$('#aiPanel').classList.add('show')};$('#closeAI').onclick=()=>{$('#aiPanel').classList.remove('show');$('#sheetBackdrop').classList.remove('show')};
$('#themeBtn').onclick=()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';persist()};
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`ai-finance-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());state={...structuredClone(defaults),...d};persist();alert('Khôi phục thành công')}catch{alert('File không hợp lệ')}e.target.value=''};
$('#resetBtn').onclick=()=>{if(confirm('Xóa toàn bộ dữ liệu?')){state=structuredClone(defaults);persist()}};
const now=new Date(),h=now.getHours();$('#greeting').textContent=h<11?'Chào buổi sáng ☀️':h<18?'Chào buổi chiều 🌤️':'Chào buổi tối 🌙';$('#dateLine').textContent=now.toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});
window.addEventListener('resize',drawChart);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
render();