const EKEY="dudeyue_expense_entries_v1",SKEY="dudeyue_expense_settings_v1",TKEY="dudeyue_expense_theme_v1";
const $=id=>document.getElementById(id);const fmt=new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0});
const defaults={groupFee:450000,dataFee:70000,phoneFee:100000,debtFee:1900000,oilKm:1500,oilCost:100000};
let entries=load(EKEY,[]),settings={...defaults,...load(SKEY,{})};
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function save(){localStorage.setItem(EKEY,JSON.stringify(entries));localStorage.setItem(SKEY,JSON.stringify(settings))}function n(id){return Number($(id).value||0)}function money(v){return fmt.format(Math.round(v||0))}function today(){const d=new Date(),o=d.getTimezoneOffset();return new Date(d-o*60000).toISOString().slice(0,10)}function fdate(s){return new Intl.DateTimeFormat("vi-VN",{weekday:"short",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(s+"T12:00:00"))}function oil(km){return settings.oilKm?(km/settings.oilKm)*settings.oilCost:0}function fixed(){return settings.groupFee+settings.dataFee+settings.phoneFee+settings.debtFee}function preview(){return n("income")-n("fuel")-n("food")-n("cigarette")-n("other")-oil(n("km"))}function readSettings(){settings={groupFee:n("groupFee"),dataFee:n("dataFee"),phoneFee:n("phoneFee"),debtFee:n("debtFee"),oilKm:Math.max(1,n("oilKm")),oilCost:n("oilCost")}}function syncSettings(){Object.entries(settings).forEach(([k,v])=>{if($(k))$(k).value=v})}function monthEntries(){const m=$("entryDate").value.slice(0,7);return entries.filter(e=>e.date.startsWith(m))}
function renderSummary(){const list=monthEntries(),inc=list.reduce((s,e)=>s+e.income,0),variable=list.reduce((s,e)=>s+e.fuel+e.food+e.cigarette+e.other+e.oilReserve,0),total=variable+fixed(),net=inc-total,sel=new Date($("entryDate").value+"T12:00:00"),days=new Date(sel.getFullYear(),sel.getMonth()+1,0).getDate(),recorded=new Set(list.map(e=>e.date)).size,avg=recorded?list.reduce((s,e)=>s+e.netBeforeFixed,0)/recorded:0;$('monthIncome').textContent=money(inc);$('monthExpense').textContent=money(total);$('monthNet').textContent=money(net);$('monthForecast').textContent=recorded?money(avg*days-fixed()):"Chưa đủ dữ liệu";$('fixedTotal').textContent=money(fixed())}
function esc(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML}function renderHistory(){const box=$('historyList'),empty=$('emptyState');box.innerHTML='';const sorted=[...entries].sort((a,b)=>b.date.localeCompare(a.date));empty.style.display=sorted.length?'none':'block';sorted.forEach(e=>{const a=document.createElement('article');a.className='history-item';a.innerHTML=`<div class="history-date"><strong>${fdate(e.date)}</strong><span>${e.note?esc(e.note):'Không có ghi chú'}</span></div><div class="history-stats"><span>Thu: ${money(e.income)}</span><span>Xăng: ${money(e.fuel)}</span><span>${e.km} km</span><span>Dầu máy: ${money(e.oilReserve)}</span></div><div class="history-net ${e.netBeforeFixed<0?'negative':''}"><strong>${money(e.netBeforeFixed)}</strong><span>Còn lại trong ngày</span><button class="delete-one" data-id="${e.id}">Xóa</button></div>`;box.appendChild(a)});document.querySelectorAll('.delete-one').forEach(b=>b.onclick=()=>{entries=entries.filter(e=>e.id!==b.dataset.id);save();renderAll()})}function renderAll(){$('todayNet').textContent=money(preview());renderSummary();renderHistory()}
$('dailyForm').onsubmit=e=>{e.preventDefault();readSettings();const date=$('entryDate').value,km=n('km'),obj={id:date+'-'+Date.now(),date,income:n('income'),fuel:n('fuel'),km,oilReserve:oil(km),food:n('food'),cigarette:n('cigarette'),other:n('other'),note:$('note').value.trim()};obj.netBeforeFixed=obj.income-obj.fuel-obj.oilReserve-obj.food-obj.cigarette-obj.other;entries=entries.filter(x=>x.date!==date);entries.push(obj);save();$('income').value='';$('km').value='';$('food').value=0;$('cigarette').value=0;$('other').value=0;$('note').value='';renderAll()};['income','fuel','km','food','cigarette','other'].forEach(id=>$(id).oninput=renderAll);$('entryDate').onchange=()=>{$('todayLabel').textContent=fdate($('entryDate').value);renderAll()};$('saveSettingsBtn').onclick=()=>{readSettings();save();renderAll();$('saveSettingsBtn').textContent='Đã lưu ✓';setTimeout(()=>$('saveSettingsBtn').textContent='Lưu thiết lập',1200)};$('clearBtn').onclick=()=>{if(entries.length&&confirm('Xóa toàn bộ lịch sử thu chi?')){entries=[];save();renderAll()}};$('themeBtn').onclick=()=>{document.body.classList.toggle('light');const l=document.body.classList.contains('light');localStorage.setItem(TKEY,l?'light':'dark');$('themeBtn').textContent=l?'🌙':'☀️'};
(()=>{const d=today();$('entryDate').value=d;$('todayLabel').textContent=fdate(d);syncSettings();if(localStorage.getItem(TKEY)==='light'){document.body.classList.add('light');$('themeBtn').textContent='🌙'}renderAll()})();
